### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fakyring** [Silverfeelin/Starbound-Wardrobe#9]
When I am trying to delete outfit the game crashes

**Comment by Silverfeelin** [comment]
More information please. Starbound log? Steps to reproduce? What add-ons do you have installed?

**Comment by Fakyring** [comment]
[starbound.log](https://github.com/Silverfeelin/Starbound-Wardrobe/files/1975165/starbound.log)
Just pressing Trash button and selecting the outfit. I don't have any addons

**Comment by Silverfeelin** [comment]
Are you sure this is the correct log? There's nothing in here.

**Comment by Fakyring** [comment]
Yep I am sure. The game just closes, without any crash logs

**Comment by Silverfeelin** [comment]
Perhaps it's related to your player file. Can you try it on a new player?

**Comment by Fakyring** [comment]
I meet this bug with one outfit only, I can delete others

**Comment by Silverfeelin** [comment]
It still makes no sense no error is being logged.

Could you send the item descriptors of your outfit that's causing the issue? If you don't know how to do that you can also send me your player file after deleting all other outfits (so I know which one to look at). Back up your player file before deleting the outfits so you don't actually lose them.
If you don't want to upload your player file here you can send it to me at Silverfeelin@gmail.com

**Comment by Silverfeelin** [comment]
Managed to recreate the issue with Puzzlemaster34's provided player file and mod list. It seemed only to occur when deleting an outfit that isn't the first in the list. I'll try to figure out what's causing it and see if I can release a fix (or restructure the outfit data to work around the issue).

**Comment by Silverfeelin** [comment]
Released in v1.3.3.3. Thank you for reporting the issue.
